### PR TITLE
Contributing Documentation

### PR DESCRIPTION
**Pull request by slifty**
This is a PR for adding guidelines for contributions that the team and any volunteers are now
in place.  They are borrowed and adapted directly from the Open Tech Strategies PSM project (http://github.com/solutionguidance/psm).

The CONTRIBUTING.md also references a few other resources that are
not yet populated (such as TESTING.md, etc).  These will not be populated until more of the
technical decisions have been made.

### CODE REVIEW

**Comment by knowtheory** [comment]
I am indifferent to neutral.  I find none of this particularly objectionable, and the branch + pull request flow seems fine.  I am unlikely to employ or enforce the guidelines around commit message writing.

**Comment by slifty** [comment]
@knowtheory I think it would be good to get the commit message portion to a point that we're all on board with following whatever protocol is written (and we could also have a like "if you want to go above and beyond do "X"")

Do you think you would be able to get behind this smaller subset around commit messages

1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Use the imperative mood in the subject line

Logic here being that we want commit messages to explain wtf is going on to make it easier to review, and ideally we would also make it easy for potential contributors to understand the shape of the project as well!

**Comment by knowtheory** [comment]
Well that's weird

**Comment by slifty** [comment]
Spoke with Ted by phone and he is cool with these changes -- mergin' time!

**Pull request merged**
